name: 'OpenVPN Session'
description: 'Open a connection to a OpenVPN session for your GitHub Actions'
author: 'Your name or organization here'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  ovpn-client:
    type: string
    description: Filepath to a `.ovpn` client [required or `ovpn-client-b64`]
    required: false
  ovpn-client-b64:
    type: string
    description: Base64 `.ovpn` file contents [required or `ovpn-client`]
    required: false
  log-save-as:
    type: string
    description: Specifiy a name to save the OpenVPN logs as an artifact
    required: false
  log-filepath:
    type: string
    description: Filepath for saving the OpenVPN logs to
    required: false
    default: '/tmp/openvpn.log'
  timeout-address:
    type: string
    description: The (private) hostname or ip for timeout testing connection to
    required: true
  timeout-seconds:
    type: number
    description: Seconds before assuming the session & connection has failed
    required: false
    default: 180

# outputs:
#   pid:
#     type: string
#     description: The process ID of the OpenVPN client running the session

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
  pre: dist/pre/index.js
