name: 'OpenVPN Session'
description: 'Open a connection to a OpenVPN session for your GitHub Actions'
author: 'Your name or organization here'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  ovpn-client:
    type: string
    description: The filepath to a OpenVPN client configuration file in `.ovpn` format. *(Only required if `ovpn-client-b64` is not specifing)*
    required: false
  ovpn-client-b64:
    type: string
    description: The base64 encoded OpenVPN client configuration file in `.ovpn` format *(Only required if `ovpn-client` is not specifing)*
    required: false
  log-save-as:
    type: string
    description: Specifiy a name to save the OpenVPN logs as an artifact.
    required: false
  log-filepath:
    type: string
    description: A path and filename (e.g. `/path/to/file.log`) to save the OpenVPN logs to.
    required: false
    default: '/tmp/openvpn.log'
  timeout-address:
    type: string
    description: The (private) hostname or ip to ping to check if the connection is up.
    required: true
  timeout-seconds:
    type: number
    description: A maximum ammount of time in seconds before exiting as a failure due to connection timeout. Default is 180 seconds or 3 minutes
    required: false
    default: 180

# outputs:
#   pid:
#     type: string
#     description: The process ID of the OpenVPN client running the session

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
  pre: dist/pre/index.js
